"""Replace unique constraint with partial index

Revision ID: 7613fe3752ac
Revises: f57ded0e2375
Create Date: 2026-08-25 22:16:10.129351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7613fe3752ac'
down_revision: Union[str, Sequence[str], None] = 'f57ded0e2375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_publish_attempt'), 'publish_attempts', type_='unique')
    op.create_index('uq_active_claim', 'publish_attempts', ['schedule_slot_id'], unique=True, postgresql_where=sa.text("result = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_claim', table_name='publish_attempts', postgresql_where=sa.text("result = 'pending'"))
    op.create_unique_constraint(op.f('uq_publish_attempt'), 'publish_attempts', ['schedule_slot_id', 'attempt_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
