"""Add unique constraint on publish_attempts

Revision ID: f57ded0e2375
Revises: 0ae626b70978
Create Date: 2026-08-25 22:05:38.271359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57ded0e2375'
down_revision: Union[str, Sequence[str], None] = '0ae626b70978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_publish_attempt', 'publish_attempts', ['schedule_slot_id', 'attempt_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_publish_attempt', 'publish_attempts', type_='unique')
    # ### end Alembic commands ###
